#config_version=6

lights:
  l_spinner:
    number:
  l_jackpot:
    number:
  l_4x:
    number:
  l_5x:
    number:
  l_2x:
    number:
  l_3x:
    number:
  l_kickout_pick_job:
    number:
  l_kickout_duel:
    number:
  l_rollover_s:
    number:
  l_rollover_h:
    number:
  l_rollover_a:
    number:
  l_rollover_r:
    number:
  l_rollover_p:
    number:
  l_rollover_e:
    number:
  l_pop_upper_center:
    number:
  l_pop_upper_left:
    number:
  l_drop_target_s:
    number:
  l_drop_target_h:
    number:
  l_drop_target_o1:
    number:
  l_drop_target_o2:
    number:
  l_drop_target_t:
    number:
  l_drop_target_e:
    number:
  l_drop_target_r:
    number:
  l_outlane:
    number:
  l_inlane:
    number:
  l_mode_posse:
    number:
  l_mode_hustle_jive:
    number:
  l_mode_target_practice:
    number:
  l_mode_check_hideout:
    number:
  l_mode_sniper:
    number:
  l_mode_sharpe:
    number:
  l_mode_ride_for_help:
    number:
  l_mode_duel:
    number:
  l_mode_bar_fight:
    number:
  l_mode_kill_all:
    number:
  l_mode_track_bandit:
    number:
  l_shoot_again:
    number:
  l_pop_bottom_upper:
    number:
  l_pop_bottom_lower:
    number:
  l_marshal:
    number:
  l_sheriff:
    number:
  l_deputy:
    number:
  l_rookie:
    number:
